openapi: 3.0.3
info:
  title: Online-store
  version: 1.0.0
  contact: {}
servers:
  - url: http://localhost:1323
paths:
  /product-create:
    post:
      summary: product-create
      description: product-create
      operationId: productCreate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                category_id:
                  type: number
                  example: 1
                description:
                  type: string
                  example: first product description
                price:
                  type: number
                  example: 100
                product_name:
                  type: string
                  example: first product
                stock_quantity:
                  type: number
                  example: 20
            examples:
              product-create:
                value:
                  category_id: 1
                  description: first product description
                  price: 100
                  product_name: first product
                  stock_quantity: 20
      responses:
        '200':
          description: ''
  /products:
    get:
      summary: All Products
      description: All Products
      operationId: allProducts
      responses:
        '200':
          description: ''
  /product/2:
    get:
      summary: Single Product
      description: Single Product
      operationId: singleProduct
      responses:
        '200':
          description: ''
  /product-update/4:
    put:
      summary: product-update
      description: product-update
      operationId: productUpdate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                category_id:
                  type: number
                  example: 1
                description:
                  type: string
                  example: 'fiadsfasdfrst product '
                price:
                  type: number
                  example: 1000000
                product_name:
                  type: string
                  example: 'adsfasdf '
                stock_quantity:
                  type: number
                  example: 2000
            examples:
              product-update:
                value:
                  category_id: 1
                  description: 'fiadsfasdfrst product '
                  price: 1000000
                  product_name: 'adsfasdf '
                  stock_quantity: 2000
      responses:
        '200':
          description: ''
  /product-delete/5:
    delete:
      summary: product-delete
      description: product-delete
      operationId: productDelete
      requestBody:
        content:
          application/json:
            examples:
              product-delete:
                value: ''
      responses:
        '200':
          description: ''
tags: []
